version: "3.8"

services:
  db:
    image: postgres
    env_file: .env
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      wish-swap-net:
  web:
    env_file: .env
    build:
      context: .
      dockerfile: dockerfiles/web.Dockerfile
    ports:
      - "${DOCKER_EXPOSE_PORT?8000}:8000"
    depends_on:
      - db
      - rabbitmq
    restart: unless-stopped
    volumes:
      - ./static:/app/static
    networks:
      wish-swap-net:
  scanner:
    env_file: .env
    build:
      context: .
      dockerfile: dockerfiles/scanner.Dockerfile
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./scanner/settings:/app/scanner/settings
    restart: unless-stopped
    networks:
      wish-swap-net:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    env_file: .env
    restart: unless-stopped
    networks:
      wish-swap-net:
  rates_checker:
    env_file: .env
    build:
      context: .
      dockerfile: dockerfiles/rates_checker.Dockerfile
    depends_on:
      - db
    restart: unless-stopped
    networks:
     wish-swap-net:
  receiver:
    env_file: .env
    build:
      context: .
      dockerfile: dockerfiles/receiver.Dockerfile
    depends_on:
      - db
      - rabbitmq
    restart: unless-stopped
    networks:
      wish-swap-net:

networks:
  wish-swap-net:
